---
layout: cv
title: Ashleigh Smith's Resume
---
# Ashleigh Smith
Accounting and Data Science Student

<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>


## Currently

Student at BYU-I
Work at Albertsons as a cake decorator
Graduate in 2026

### Specialized in

Accounting and Data Science


### Research interests

Cooling, power series, optics, alchemy, planetary motions, apples.


## Education

`September 2023 - Current`
__Brigham Young University-Idaho.__




## Experience

`January 2025-April 2025`
Tax Accountant Intern, Fox Peterson Entrepreneurial Accountants

`January 2024- December 2024`
Student Expense Report Analyst, Brigham Young University - Idaho

`June 2021- September 2023`
Team Trainer, Chick-fil-A




## Leadership/Volunteerism

__Rexburg__, Idaho

- Obtained leadership skills as co-captain of the Varsity Volleyball team
- Volunteered at blood drives and other service activities as a member of the National Honors Society
- Supervised children for over eight families gaining trust through responsibility and punctuality


### Skills & Software

- Proficient in Python and Excel
- Currently learning Power BI and SQL
- Have a typing Speed of 62 WPM with 98% accuracy


## Occupation

`2025`
__Rexburg__, Idaho

- Cake Decorator




<!-- ### Footer

Last updated: May 2013 -->